import uuid
from io import BytesIO

import boto3
from botocore.exceptions import ClientError

from app.config import settings

# --- S3 Client ---
# We create the client once at module level and reuse it.
# The client manages a connection pool internally, so creating
# one per request would be wasteful.
#
# We pass credentials explicitly (from our .env) rather than relying
# on boto3's default credential chain. This makes our configuration
# explicit and predictable. In production on AWS, you'd remove these
# parameters and let boto3 auto-discover credentials from the IAM role.
s3_client = boto3.client(
    "s3",
    aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
    aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
    region_name=settings.AWS_REGION,
)


def generate_s3_key(user_id: str, original_filename: str) -> str:
    """
    Generate a unique S3 object key for a file.
    
    Format: users/{user_id}/{uuid}_{original_filename}
    
    Why not just use the original filename?
    1. Two users could upload files with the same name
    2. A user could upload the same file twice
    3. Filenames could contain characters that cause problems in S3/URLs
    4. Predictable keys could let attackers guess file locations
    
    The UUID prefix ensures every key is unique.
    The user_id prefix acts as a logical folder, making it easy to
    find all files belonging to a specific user in S3.
    
    Example: users/abc123/550e8400_photo.jpg
    """
    unique_id = uuid.uuid4().hex[:12]  # Short but unique enough
    safe_filename = original_filename.replace(" ", "_")
    return f"users/{user_id}/{unique_id}_{safe_filename}"


def upload_file_to_s3(file_content: bytes, s3_key: str, content_type: str) -> bool:
    """
    Upload a file to S3.
    
    Args:
        file_content: The raw bytes of the file
        s3_key: The S3 object key (path) generated by generate_s3_key()
        content_type: MIME type (e.g., "image/jpeg", "application/pdf")
    
    Returns:
        True if upload succeeded, False otherwise
    
    How it works:
    1. boto3 sends a PutObject request to the S3 API
    2. S3 stores the bytes at the specified key in our bucket
    3. The ContentType metadata is stored with the object so
       browsers know how to handle the file when downloaded
    """
    try:
        s3_client.upload_fileobj(
            BytesIO(file_content),
            settings.S3_BUCKET_NAME,
            s3_key,
            ExtraArgs={"ContentType": content_type},
        )
        return True
    except ClientError as e:
        print(f"S3 upload error: {e}")
        return False


def generate_presigned_url(s3_key: str, expiration: int = 3600) -> str | None:
    """
    Generate a pre-signed URL to download a file from S3.
    
    What is a pre-signed URL?
    Our S3 bucket is PRIVATE — nobody can access files directly.
    A pre-signed URL is a temporary, signed link that grants
    read access to ONE specific file for a limited time.
    
    How it works:
    1. We create a URL that includes a cryptographic signature
    2. The signature proves that someone with valid credentials authorized this access
    3. S3 verifies the signature and serves the file
    4. After expiration (default: 1 hour), the URL stops working
    
    Why pre-signed URLs instead of streaming through our backend?
    - Performance: The client downloads directly from S3 (fast CDN)
    - Scalability: Our backend doesn't become a bottleneck for file downloads
    - Cost: Reduces bandwidth through our server
    
    The URL looks like:
    https://bucket.s3.amazonaws.com/key?X-Amz-Signature=...&X-Amz-Expires=3600
    
    Args:
        s3_key: The S3 object key
        expiration: Seconds until the URL expires (default: 1 hour)
    
    Returns:
        The pre-signed URL string, or None if generation fails
    """
    try:
        url = s3_client.generate_presigned_url(
            "get_object",
            Params={
                "Bucket": settings.S3_BUCKET_NAME,
                "Key": s3_key,
            },
            ExpiresIn=expiration,
        )
        return url
    except ClientError as e:
        print(f"S3 pre-signed URL error: {e}")
        return None


def delete_file_from_s3(s3_key: str) -> bool:
    """
    Delete a file from S3.
    
    Args:
        s3_key: The S3 object key to delete
    
    Returns:
        True if deletion succeeded, False otherwise
    
    Note: S3 returns success even if the key doesn't exist.
    This is by design — delete is idempotent (safe to call multiple times).
    """
    try:
        s3_client.delete_object(
            Bucket=settings.S3_BUCKET_NAME,
            Key=s3_key,
        )
        return True
    except ClientError as e:
        print(f"S3 delete error: {e}")
        return False
